-- CEDOC Accident Recording and Reporting System
-- Clean standard relational schema for documentation and database design.
-- Public business tables only: 12 tables from the official database.

CREATE TABLE users (
    user_id BIGINT NOT NULL,
    cedoc_id VARCHAR NOT NULL,
    username VARCHAR,
    password VARCHAR,
    first_name VARCHAR,
    middle_name VARCHAR,
    surname VARCHAR,
    cedoc_name VARCHAR,
    email_address VARCHAR,
    contacts VARCHAR,
    category VARCHAR,
    designation VARCHAR,
    role VARCHAR,
    account_type VARCHAR,
    responder_type VARCHAR,
    vehicle_type VARCHAR,
    status VARCHAR,
    is_logged_in BOOLEAN NOT NULL,
    session_state VARCHAR NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (user_id),
    CONSTRAINT uq_users_cedoc_id UNIQUE (cedoc_id)
);

CREATE TABLE user_time_render (
    cedoc_id VARCHAR NOT NULL,
    full_name VARCHAR,
    activity_date DATE,
    login_at TIMESTAMP,
    logout_at TIMESTAMP,
    render_seconds BIGINT NOT NULL,
    render_time VARCHAR NOT NULL,
    case_report_created INTEGER NOT NULL,
    active_state VARCHAR NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_user_time_render PRIMARY KEY (cedoc_id),
    CONSTRAINT fk_user_time_render_user FOREIGN KEY (cedoc_id) REFERENCES users(cedoc_id)
);

CREATE TABLE cedoc_id_year_sequence (
    registration_year INTEGER NOT NULL,
    last_sequence INTEGER NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_cedoc_id_year_sequence PRIMARY KEY (registration_year)
);

CREATE TABLE system_setting (
    setting_key VARCHAR NOT NULL,
    system_name VARCHAR NOT NULL,
    organization_name VARCHAR NOT NULL,
    contact_number VARCHAR NOT NULL,
    email_address VARCHAR NOT NULL,
    time_zone VARCHAR NOT NULL,
    theme_mode VARCHAR NOT NULL,
    accent_color VARCHAR NOT NULL,
    sidebar_style VARCHAR NOT NULL,
    log_style VARCHAR NOT NULL,
    cmd_theme VARCHAR NOT NULL,
    updated_by VARCHAR NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_system_setting PRIMARY KEY (setting_key)
);

CREATE TABLE accident_cases (
    case_id VARCHAR NOT NULL,
    case_number VARCHAR,
    case_date VARCHAR,
    time_label VARCHAR,
    case_type VARCHAR NOT NULL,
    name_of_caller VARCHAR,
    contact_number VARCHAR,
    call_taker VARCHAR,
    concern VARCHAR,
    action_taken VARCHAR,
    location VARCHAR NOT NULL,
    barangay VARCHAR,
    street_address VARCHAR,
    patient_name VARCHAR,
    status VARCHAR NOT NULL,
    created_by_cedoc_id VARCHAR NOT NULL,
    created_by_name VARCHAR NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_accident_cases PRIMARY KEY (case_id),
    CONSTRAINT fk_accident_cases_created_by FOREIGN KEY (created_by_cedoc_id) REFERENCES users(cedoc_id)
);

CREATE TABLE medical_reports (
    report_id VARCHAR NOT NULL,
    case_id VARCHAR,
    case_number VARCHAR,
    case_date VARCHAR,
    case_time VARCHAR,
    patient_name VARCHAR,
    age INTEGER,
    gender VARCHAR,
    birthdate VARCHAR,
    location VARCHAR,
    address VARCHAR,
    contact_number VARCHAR,
    case_type VARCHAR,
    vital_signs VARCHAR,
    service_provided VARCHAR,
    vehicle_used VARCHAR,
    team_leader VARCHAR,
    status VARCHAR NOT NULL,
    draft BOOLEAN NOT NULL,
    created_by_cedoc_id VARCHAR NOT NULL,
    created_by_name VARCHAR NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_medical_reports PRIMARY KEY (report_id),
    CONSTRAINT fk_medical_reports_case FOREIGN KEY (case_id) REFERENCES accident_cases(case_id),
    CONSTRAINT fk_medical_reports_created_by FOREIGN KEY (created_by_cedoc_id) REFERENCES users(cedoc_id)
);

CREATE TABLE fire_reports (
    report_id VARCHAR NOT NULL,
    case_id VARCHAR,
    location VARCHAR,
    date_started DATE,
    time_started VARCHAR,
    time_ended VARCHAR,
    cause_of_fire VARCHAR,
    origin_of_fire VARCHAR,
    number_of_deaths INTEGER,
    number_of_injuries INTEGER,
    estimated_cost_of_damage DOUBLE PRECISION,
    establishments_or_houses_burned INTEGER,
    families_affected INTEGER,
    investigator_on_case VARCHAR,
    fireground_commander VARCHAR,
    total_people_affected INTEGER,
    remarks VARCHAR,
    status VARCHAR NOT NULL,
    draft BOOLEAN NOT NULL,
    created_by_cedoc_id VARCHAR NOT NULL,
    created_by_name VARCHAR NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_fire_reports PRIMARY KEY (report_id),
    CONSTRAINT fk_fire_reports_case FOREIGN KEY (case_id) REFERENCES accident_cases(case_id),
    CONSTRAINT fk_fire_reports_created_by FOREIGN KEY (created_by_cedoc_id) REFERENCES users(cedoc_id)
);

CREATE TABLE traffic_reports (
    report_id VARCHAR NOT NULL,
    case_id VARCHAR,
    responder_name VARCHAR,
    accident_date VARCHAR,
    accident_time VARCHAR,
    address VARCHAR,
    barangay VARCHAR,
    vehicles_involved INTEGER,
    versus_another_vehicle BOOLEAN NOT NULL,
    versus_pedestrian BOOLEAN NOT NULL,
    versus_fixed_object BOOLEAN NOT NULL,
    versus_animal BOOLEAN NOT NULL,
    type_fatal BOOLEAN NOT NULL,
    type_non_fatal BOOLEAN NOT NULL,
    type_damage_to_property BOOLEAN NOT NULL,
    type_rear_end BOOLEAN NOT NULL,
    type_side_swipe_same_direction BOOLEAN NOT NULL,
    type_head_on BOOLEAN NOT NULL,
    type_angle BOOLEAN NOT NULL,
    type_side_swipe_opposite_direction BOOLEAN NOT NULL,
    type_hit_and_run BOOLEAN NOT NULL,
    type_roll_over BOOLEAN NOT NULL,
    type_multiple_vehicle_collision BOOLEAN NOT NULL,
    type_single_vehicle_accident BOOLEAN NOT NULL,
    involved_vehicles VARCHAR,
    notes VARCHAR,
    status VARCHAR NOT NULL,
    draft BOOLEAN NOT NULL,
    created_by_cedoc_id VARCHAR NOT NULL,
    created_by_name VARCHAR NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_traffic_reports PRIMARY KEY (report_id),
    CONSTRAINT fk_traffic_reports_case FOREIGN KEY (case_id) REFERENCES accident_cases(case_id),
    CONSTRAINT fk_traffic_reports_created_by FOREIGN KEY (created_by_cedoc_id) REFERENCES users(cedoc_id)
);

CREATE TABLE accident_cases_archive (
    case_id VARCHAR NOT NULL,
    case_number VARCHAR,
    case_type VARCHAR NOT NULL,
    location VARCHAR NOT NULL,
    barangay VARCHAR,
    status VARCHAR NOT NULL,
    created_by_cedoc_id VARCHAR NOT NULL,
    created_by_name VARCHAR NOT NULL,
    created_at TIMESTAMP NOT NULL,
    archived_by_cedoc_id VARCHAR NOT NULL,
    archived_by_name VARCHAR NOT NULL,
    archived_at TIMESTAMP NOT NULL,
    archive_reason VARCHAR NOT NULL,
    CONSTRAINT pk_accident_cases_archive PRIMARY KEY (case_id),
    CONSTRAINT fk_accident_archive_case FOREIGN KEY (case_id) REFERENCES accident_cases(case_id),
    CONSTRAINT fk_accident_archive_created_by FOREIGN KEY (created_by_cedoc_id) REFERENCES users(cedoc_id),
    CONSTRAINT fk_accident_archive_archived_by FOREIGN KEY (archived_by_cedoc_id) REFERENCES users(cedoc_id)
);

CREATE TABLE medical_reports_archive (
    report_id VARCHAR NOT NULL,
    case_id VARCHAR,
    case_number VARCHAR,
    patient_name VARCHAR,
    case_type VARCHAR,
    status VARCHAR NOT NULL,
    created_by_cedoc_id VARCHAR NOT NULL,
    created_by_name VARCHAR NOT NULL,
    created_at TIMESTAMP NOT NULL,
    archived_by_cedoc_id VARCHAR NOT NULL,
    archived_by_name VARCHAR NOT NULL,
    archived_at TIMESTAMP NOT NULL,
    archive_reason VARCHAR NOT NULL,
    CONSTRAINT pk_medical_reports_archive PRIMARY KEY (report_id),
    CONSTRAINT fk_medical_archive_report FOREIGN KEY (report_id) REFERENCES medical_reports(report_id),
    CONSTRAINT fk_medical_archive_case FOREIGN KEY (case_id) REFERENCES accident_cases(case_id),
    CONSTRAINT fk_medical_archive_created_by FOREIGN KEY (created_by_cedoc_id) REFERENCES users(cedoc_id),
    CONSTRAINT fk_medical_archive_archived_by FOREIGN KEY (archived_by_cedoc_id) REFERENCES users(cedoc_id)
);

CREATE TABLE fire_reports_archive (
    report_id VARCHAR NOT NULL,
    case_id VARCHAR,
    location VARCHAR,
    date_started DATE,
    cause_of_fire VARCHAR,
    status VARCHAR NOT NULL,
    created_by_cedoc_id VARCHAR NOT NULL,
    created_by_name VARCHAR NOT NULL,
    created_at TIMESTAMP NOT NULL,
    archived_by_cedoc_id VARCHAR NOT NULL,
    archived_by_name VARCHAR NOT NULL,
    archived_at TIMESTAMP NOT NULL,
    archive_reason VARCHAR NOT NULL,
    CONSTRAINT pk_fire_reports_archive PRIMARY KEY (report_id),
    CONSTRAINT fk_fire_archive_report FOREIGN KEY (report_id) REFERENCES fire_reports(report_id),
    CONSTRAINT fk_fire_archive_case FOREIGN KEY (case_id) REFERENCES accident_cases(case_id),
    CONSTRAINT fk_fire_archive_created_by FOREIGN KEY (created_by_cedoc_id) REFERENCES users(cedoc_id),
    CONSTRAINT fk_fire_archive_archived_by FOREIGN KEY (archived_by_cedoc_id) REFERENCES users(cedoc_id)
);

CREATE TABLE traffic_reports_archive (
    report_id VARCHAR NOT NULL,
    case_id VARCHAR,
    responder_name VARCHAR,
    accident_date VARCHAR,
    address VARCHAR,
    barangay VARCHAR,
    status VARCHAR NOT NULL,
    created_by_cedoc_id VARCHAR NOT NULL,
    created_by_name VARCHAR NOT NULL,
    created_at TIMESTAMP NOT NULL,
    archived_by_cedoc_id VARCHAR NOT NULL,
    archived_by_name VARCHAR NOT NULL,
    archived_at TIMESTAMP NOT NULL,
    archive_reason VARCHAR NOT NULL,
    CONSTRAINT pk_traffic_reports_archive PRIMARY KEY (report_id),
    CONSTRAINT fk_traffic_archive_report FOREIGN KEY (report_id) REFERENCES traffic_reports(report_id),
    CONSTRAINT fk_traffic_archive_case FOREIGN KEY (case_id) REFERENCES accident_cases(case_id),
    CONSTRAINT fk_traffic_archive_created_by FOREIGN KEY (created_by_cedoc_id) REFERENCES users(cedoc_id),
    CONSTRAINT fk_traffic_archive_archived_by FOREIGN KEY (archived_by_cedoc_id) REFERENCES users(cedoc_id)
);
